server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hogar360_visit_db
    username: root
    password: toor
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET}
  user: AUTH0JWT_BACKEND
  expiration: 86400000

#logging:
#  level:
#    root: debug